services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/tharun-r1705/n8n
    dockerfilePath: docker/images/n8n/Dockerfile
    plan: free
    envVars:
      - key: N8N_SECURE_COOKIE
        value: "false"
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: "https://n8n.onrender.com/"
      - key: N8N_EDITOR_BASE_URL
        value: "https://n8n.onrender.com/"
      - key: N8N_PUBLIC_API_BASE_URL
        value: "https://n8n.onrender.com/"
      - key: GENERIC_TIMEZONE
        value: "Asia/Kolkata"
